version: '3'

services:
  backend:
    container_name: backend-node
    build:
      context: ./js
    ports:
      - 3412:3412

  frontend:
    container_name: frontend-angularjs
    build: .
    ports:
       - 8080:8080