version: '3'

services:
  docker-mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=1478
      - MYSQL_DATABASE=dchat
      - MYSQL_USER=jcarlos
      - MYSQL_PASSWORD=1478
    ports:
      - 3306:3306

  api-container:
    image: joaocarlosp/apigo:latest
    container_name: api-container
    restart: unless-stopped
    ports:
       - 8080:8080
    depends_on:
       - docker-mysql

  frontend:
    image: joaocarlosp/angular:latest
    container_name: angular
    restart: unless-stopped
    ports:
       - 4200:80
    depends_on:
       - api-container